site_name: Advanced programming of robots in ROS
site_url: https://abc-irobotics.github.io/advanced_ros_course_materials_en/
site_description: Materials for the course Advanced programming of robots in ROS at Óbuda University
site_author: Tamas D. Nagy
repo_url: https://github.com/ABC-iRobotics/advanced_ros_course_materials_en

nav:
  - Home: index.md
  - Materials:
      - 1. Introduction, System setup: 01_system_setup.md
      - 2. Linux and ROS principles: 02_linux_ros_principles.md
      - 3. Python alapismeretek,  ROS Publisher, ROS Subscriber: 03_python_principles.md
      - 4. Versioning, Git: 04_git.md
      - 5. Principles of robotics, da Vinci: 05_da_vinci.md
      - 6. Roslaunch, msg, action, service: 06_roslaunch.md
      - 7. Kinematics, inverse kinematics: 07_robotics_principles.md
  - Projects: projects.md


theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  language: hu
  features:
    - navigation.tabs
    - toc.integrate



extra:
  alternate:
    - name: English
      link: https://abc-irobotics.github.io/advanced_ros_course_materials_en/
      lang: en

    - name: Hungarian
      link: https://abc-irobotics.github.io/advanced_ros_course_materials_hu/
      lang: hu

plugins:
  - search
  - pdf-export


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables


copyright: Copyright &copy; 2023 <a href="mailto:tamas.daniel.nagy@irob.uni-obuda.hu">Tamas D. Nagy</a>.


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

